
SELECT UGD.TITLE, UGD.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS,
    LEFT(STR_TO_DATE(UGR.CREATED_DATE, '%Y-%m-%d'), 10) AS CREATED_DATE
FROM USED_GOODS_BOARD  UGD
    INNER JOIN USED_GOODS_REPLY UGR
ON UGD.BOARD_ID = UGR.BOARD_ID
WHERE UGD.CREATED_DATE >= '2022-10-01'
  AND UGD.CREATED_DATE < '2022-11-01'
ORDER BY UGR.CREATED_DATE ASC, UGD.TITLE ASC;
