# -- 코드를 입력하세요
SELECT
    YEAR(T1.SALES_DATE) AS YEAR
, MONTH(T1.SALES_DATE) AS MONTH
, T2.GENDER AS GENDER
, COUNT(DISTINCT(T1.USER_ID)) AS USERS
FROM ONLINE_SALE T1
    INNER JOIN USER_INFO T2 ON T1.USER_ID = T2.USER_ID
WHERE T2.GENDER IS NOT NULL
GROUP BY SUBSTRING(T1.SALES_DATE, 1, 4), SUBSTRING(T1.SALES_DATE, 6, 2), T2.GENDER
ORDER BY YEAR, MONTH, GENDER ASC