SELECT 
T1.ID
, T2.FISH_NAME
, T1.LENGTH
FROM (
    SELECT *, 
    ROW_NUMBER() OVER (
        PARTITION BY FISH_TYPE ORDER  BY LENGTH DESC
    ) AS RN
    FROM FISH_INFO    
) T1
INNER JOIN FISH_NAME_INFO T2 ON T1.FISH_TYPE = T2.FISH_TYPE
WHERE T1.RN = 1 AND T1.LENGTH > 10
ORDER BY ID ASC
