-- 코드를 작성해주세요
SELECT   
T2.ITEM_ID
, (
SELECT ITEM_NAME FROM ITEM_INFO WHERE ITEM_ID = T2.ITEM_ID
) AS ITEM_NAME
, (
SELECT RARITY FROM ITEM_INFO WHERE ITEM_ID = T2.ITEM_ID
) AS RARITY
FROM ITEM_INFO T1
INNER JOIN ITEM_TREE T2 ON T2.PARENT_ITEM_ID = T1.ITEM_ID
WHERE T1.RARITY = 'RARE'
ORDER BY T2.ITEM_ID DESC
