# -- 코드를 입력하세요
SELECT
USER_ID
, PRODUCT_ID
# , COUNT(1) AS CNT
FROM ONLINE_SALE 
GROUP BY USER_ID, PRODUCT_ID
HAVING  COUNT(1) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC

# select * FROM ONLINE_SALE 
# order by USER_ID, PRODUCT_ID
